Repository compas-dev/compas, pull requests merged in 2021-03, with the labels that each got.

#786 Switch to static API
  CHANGELOG.md
  setup.cfg
  src/compas/datastructures/__init__.py
  src/compas/datastructures/mesh/__init__.py
  src/compas/datastructures/mesh/_mesh.py
  src/compas/datastructures/mesh/planarisation_numpy.py
  src/compas/datastructures/network/__init__.py
  src/compas/datastructures/network/planarity.py
  src/compas/datastructures/network/planarity_.py
  src/compas/files/__init__.py
  src/compas/geometry/__init__.py
  src/compas/geometry/_core/basic.py
  src/compas/geometry/transformations/transformations.py
  src/compas/geometry/transformations/transformations_numpy.py
  src/compas/interop/__init__.py
  src/compas/numerical/__init__.py
  src/compas/robots/__init__.py
  src/compas/rpc/__init__.py
  src/compas/topology/__init__.py
  src/compas/utilities/__init__.py
  src/compas_blender/artists/__init__.py
  src/compas_blender/geometry/__init__.py
  src/compas_blender/ui/__init__.py
  src/compas_blender/utilities/__init__.py
  src/compas_ghpython/artists/__init__.py
  src/compas_ghpython/utilities/__init__.py
  src/compas_plotters/__init__.py
  src/compas_plotters/artists/__init__.py
  src/compas_plotters/core/__init__.py
  src/compas_rhino/artists/__init__.py
  src/compas_rhino/conduits/__init__.py
  src/compas_rhino/forms/__init__.py
  src/compas_rhino/geometry/__init__.py
  src/compas_rhino/objects/__init__.py
  src/compas_rhino/ui/__init__.py
  src/compas_rhino/utilities/__init__.py
  tests/compas/datastructures/test_mesh_operations.py
  tests/compas/datastructures/test_mesh_subd.py
Labels: enhancement, no changelog

#793 Add twitter badge
  README.md
Labels: no changelog

#778 Update `Box` transform
  CHANGELOG.md
  src/compas/geometry/shapes/box.py
Labels: bug
