Repository compas-dev/compas, pull requests merged in 2023-12, with the labels that each got.

#1217 added code contribution guide
  docs/_images/ghpython_custom.jpg
  docs/_images/vscode_git.JPG
  docs/devguide/code.rst
  docs/devguide/ghcomponent.rst
  docs/devguide/index.rst
  docs/devguide/setup.rst
  docs/devguide/workflow.rst
  docs/userguide/installation.rst
Labels: documentation, no changelog

#1228 Fix copyright notice in license file
  LICENSE
Labels: no changelog

#1176 Introduce the compas.tolerance module
  CHANGELOG.md
  docs/api/compas.geometry.rst
  docs/api/compas.rst
  docs/api/compas.tolerance.rst
  docs/userguide/index.rst
  src/compas/__init__.py
  src/compas/datastructures/mesh/clean.py
  src/compas/datastructures/mesh/join.py
  src/compas/datastructures/mesh/mesh.py
  src/compas/datastructures/network/network.py
  src/compas/datastructures/network/operations/join.py
  src/compas/datastructures/volmesh/volmesh.py
  src/compas/files/obj.py
  src/compas/files/stl.py
  src/compas/geometry/__init__.py
  src/compas/geometry/_core/_algebra.py
  src/compas/geometry/_core/angles.py
  src/compas/geometry/_core/distance.py
  src/compas/geometry/_core/predicates_2.py
  src/compas/geometry/_core/predicates_3.py
  src/compas/geometry/_core/quaternions.py
  src/compas/geometry/_core/transformations.py
  src/compas/geometry/bbox_numpy.py
  src/compas/geometry/curves/curve.py
  src/compas/geometry/curves/polyline.py
  src/compas/geometry/frame.py
  src/compas/geometry/icp_numpy.py
  src/compas/geometry/intersections.py
  src/compas/geometry/offset.py
  src/compas/geometry/plane.py
  src/compas/geometry/point.py
  src/compas/geometry/pointcloud.py
  src/compas/geometry/quaternion.py
  src/compas/geometry/rotation.py
  src/compas/geometry/transformation.py
  src/compas/geometry/vector.py
  src/compas/tolerance.py
  src/compas_rhino/conversions/surfaces.py
  src/compas_rhino/utilities/constructors.py
  tests/compas/compas_api.json
  tests/compas/compas_api_ipy.json
  tests/compas/datastructures/test_mesh.py
  tests/compas/files/test_gltf.py
  tests/compas/files/test_stl.py
  tests/compas/geometry/test_core.py
Labels: enhancement
